# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - registration-Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and publish Function App
        run: dotnet publish backend/backend.csproj -c Release -o ./publish

      - name: "Deploy to Azure Function App"
        uses: Azure/functions-action@v1
        with:
          app-name: "registration-Function"
          slot-name: "Production"
          package: "./publish"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F8F387D1C6C948988CC373261C755995 }}
